[shared]
gatewaysvc = "localhost:17000"

[grpc]
address = "0.0.0.0:17000"

[grpc.services.gateway]
authregistrysvc = "localhost:17000"
storageregistrysvc = "localhost:17000"
preferencessvc = "localhost:17000"
userprovidersvc = "localhost:17000"
usershareprovidersvc = "localhost:17000"
publicshareprovidersvc = "localhost:17000"
ocmcoresvc = "localhost:17000"
ocmshareprovidersvc = "localhost:17000"
ocminvitemanagersvc = "localhost:17000"
ocmproviderauthorizersvc = "localhost:17000"
commit_share_to_storage_grant = false
datagateway = "http://localhost:17001/data"
transfer_expires = 6 # give it a moment

[grpc.services.authregistry]
driver = "static"

[grpc.services.authregistry.drivers.static.rules]
basic = "localhost:17000"

[grpc.services.storageregistry]
driver = "static"

[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = {"address" = "localhost:17000"}
"123e4567-e89b-12d3-a456-426655440000" = {"address" = "localhost:17000"}

[grpc.services.usershareprovider]
driver = "memory"

[grpc.services.ocmcore]
driver = "nextcloud"

[grpc.services.ocmcore.drivers.nextcloud]
end_point = "http://localhost:8080/index.php/apps/sciencemesh/"
mock_http = false

[grpc.services.ocminvitemanager]
driver = "json"

[grpc.services.ocmshareprovider]
driver = "nextcloud"

[grpc.services.ocmshareprovider.drivers.nextcloud]
end_point = "http://localhost:8080/index.php/apps/sciencemesh/"
mock_http = false

[grpc.services.ocmproviderauthorizer]
driver = "json"

[grpc.services.ocmproviderauthorizer.drivers.json]
providers = "providers.demo.json"

[grpc.services.publicshareprovider]
driver = "memory"

[grpc.services.storageprovider]
driver = "nextcloud"

[grpc.services.storageprovider.drivers.nextcloud]
end_point = "http://localhost:8080/index.php/apps/sciencemesh/"
mock_http = false

[grpc.services.authprovider]
auth_manager = "json"

[grpc.services.authprovider.auth_managers.json]
users = "users.demo.json"

[grpc.services.userprovider]
driver = "json"

[grpc.services.userprovider.drivers.json]
users = "users.demo.json"

[http]
enabled_services = ["ocmd"]
enabled_middlewares = ["providerauthorizer", "cors"]
address = "0.0.0.0:17001"

[http.services.dataprovider]
driver = "localhome"

[http.services.prometheus]
[http.services.sysinfo]

[http.services.dataprovider.drivers.localhome]
user_layout = "{{.Username}}"

[http.services.ocmd]
prefix = "ocm"

[http.middlewares.providerauthorizer]
driver = "json"

[http.middlewares.providerauthorizer.drivers.json]
providers = "providers.demo.json"

[http.services.ocs]
prefix = "ocs"

[http.services.ocdav]

[http.middlewares.cors]
